<h1>Вход в систему</h1>
<ul class="nav nav-tabs">
    <li class="active"><a href="#login" data-toggle="tab">Логин</a></li>
    <li><a href="#reg" data-toggle="tab">Регистрация</a></li>
</ul>
<div id="myTabContent" class="tab-content">
    <div class="tab-pane fade active in" id="login">
        <h1>Логин</h1>
    </div>
    <div class="tab-pane fade" id="reg">
        <h1>Registration</h1>
        <?php
        /*$form = $this->form;
        $form->setAttribute('action', $this->url('auth/default', array('controller' => 'registration', 'action' => 'index')));
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formRow($form->get('usrName'));
        echo $this->formRow($form->get('usrEmail'));
        echo $this->formRow($form->get('usrPassword'));
        echo $this->formRow($form->get('usrPasswordConfirm'));
        echo $this->formRow($form->get('captcha'));
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();*/
        ?>
    </div>

</div>